- doi: 10.1038/s41586-023-06630-3
  image: USAtlas.gif
  buttons:
    - type: website
      link: https://www.nature.com/articles/s41586-023-06630-3
    - type: pdf
      link: atlas.pdf
  tags:
    - highlight
    - fetal-brain-characteristics
